# Copyright 2023-2025 The Milton Hirsch Institute, B.V.
# SPDX-License-Identifier: Apache-2.0

name: Release Python package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: [self-hosted, Linux, ARM64, packagemaze-linux-local]
    name: Builds and publishes release.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: python -m pip install --upgrade poetry

      - name: Extract version from poetry
        run: |
          echo release_version=$(poetry version -s) >> $GITHUB_ENV

      - name: Make sure version matches GITHUB_REF
        run: test "refs/tags/v${{ env.release_version }}" == "$GITHUB_REF"

      - name: Build sdist
        run: poetry build -f sdist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
